# Generated by Django 5.2.6 on 2025-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_chapter_image_alter_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(),
        ),
    ]
